# Generated by Django 4.0.4 on 2022-06-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_listing_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='start_price',
            new_name='start_bid',
        ),
    ]
