# Generated by Django 4.0.4 on 2022-06-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_start_price_auction_listing_start_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='start_bid',
            new_name='starting_bid',
        ),
    ]
