# Generated by Django 4.0.4 on 2022-06-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_start_bid_auction_listing_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='photo',
            field=models.CharField(max_length=128),
        ),
    ]
