# Generated by Django 4.0.4 on 2022-07-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_listing_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
