# Generated by Django 4.0.4 on 2022-07-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_listing_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
    ]
