# Generated by Django 4.0.4 on 2022-07-02 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_listing_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auction_listing', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
