# Generated by Django 4.0.4 on 2022-07-03 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_watchlist_item_watchlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='watchers',
            field=models.ManyToManyField(blank=True, null=True, related_name='watched_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='watchlist',
        ),
    ]
