# Generated by Django 4.0.4 on 2022-07-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auction_listing_watchers_delete_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ManyToManyField(blank=True, null=True, related_name='last_bidder', to='auctions.auction_listing'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
    ]
