# Generated by Django 4.0.4 on 2022-07-03 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_bid_listing_alter_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ManyToManyField(blank=True, null=True, related_name='bids', to='auctions.auction_listing'),
        ),
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
