# Generated by Django 4.0.4 on 2022-07-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auction_listing_current_bid_bid_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='bidding',
        ),
    ]
