# Generated by Django 4.0.4 on 2022-07-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_bid_listing_bid_listing_remove_bid_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
